name: pokedex_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/pikachu.png
    - assets/img/pokeball.png

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/Press_Start_2P/PressStart2P-Regular.ttf